Julia's debug build and debug CI test failing
mmtk/julia pull request #26
Opened 2023-08-09 01:18 UTC by udesou

Fixed issue that prevented building Julia or running tests with Julia's debug build. The MMTk library wasn't being copied and the tests used `julia` instead of `julia-debug` before running tests.

2023-08-09 01:32 UTC, qinsoon requested changes

2023-08-09 01:32 UTC, qinsoon commented on Makefile
> -	@PATH="$(PATH):$(dir $(JULIA_EXECUTABLE))" julia $(call cygpath_w,$(JULIAHOME)/contrib/check-whitespace.jl)
I don't feel we want to change this. It looks like this is how Julia runs 'check-whitespace.jl'. There is no point to run it with a debug build. They just use Julia as a script to check white space.

2023-08-09 01:32 UTC, qinsoon commented on src/Makefile
> -MMTK_DOBJS := $(MMTK_SRCS:%=$(MMTK_JULIA_INC)/%.dbg.obj)
I think, in a debug build (`make debug`), two executables are produced, `julia` and `julia-debug`. Do we need `$(MMTK_LIB_DST)` twice?

2023-08-09 01:34 UTC, udesou commented on Makefile
> -	@PATH="$(PATH):$(dir $(JULIA_EXECUTABLE))" julia $(call cygpath_w,$(JULIAHOME)/contrib/check-whitespace.jl)
The issue is that when I run `make testall debug`, I get an error saying that `julia` isn't found (something like that). The change I proposed fixed that issue.

2023-08-09 01:41 UTC, udesou commented on src/Makefile
> -MMTK_DOBJS := $(MMTK_SRCS:%=$(MMTK_JULIA_INC)/%.dbg.obj)
Hmm, again, I get an error building Julia with `make debug` if I don't use `$(MMTK_LIB_DST)` there. The target at [line 392](https://github.com/mmtk/julia/blob/39530f9e4c9ca2d66bf152d4d125e44a43c9caef/src/Makefile#L398): 
```
$(build_shlibdir)/libjulia-internal-debug.$(JL_MAJOR_MINOR_SHLIB_EXT): $(SRCDIR)/julia.expmap $(DOBJS) $(MMTK_DOBJS) $(BUILDDIR)/flisp/libflisp-debug.a 
```
uses `$(MMTK_DOBJS)` and not `$(MMTK_OBJS)`, and therefore fails on a debug build.

2023-08-09 01:48 UTC, qinsoon commented on src/Makefile
> -MMTK_DOBJS := $(MMTK_SRCS:%=$(MMTK_JULIA_INC)/%.dbg.obj)
Yeah. I see.

2023-08-09 02:25 UTC, qinsoon approved these changes
LGTM

2023-08-09 02:26 UTC, qinsoon commented on Makefile
> -	@PATH="$(PATH):$(dir $(JULIA_EXECUTABLE))" julia $(call cygpath_w,$(JULIAHOME)/contrib/check-whitespace.jl)
Looks good to me. I thought `make debug` would build both `julia` and `julia-debug`. But it seems not the case.

2023-08-23 01:17 UTC, qinsoon commented
Should we merge this?

2023-08-23 01:18 UTC, udesou commented
Yes. Sorry, I forgot about this PR.

2023-08-23 01:18 UTC, merged